/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getMe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["updateMe"];
        trace?: never;
    };
    "/devices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listDevices"];
        put?: never;
        post: operations["registerDevice"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/devices/{deviceId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["deleteDevice"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/journeys": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listJourneys"];
        put?: never;
        post: operations["createJourney"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/journeys/{journeyId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                journeyId: components["parameters"]["JourneyID"];
            };
            cookie?: never;
        };
        get: operations["getJourney"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["updateJourney"];
        trace?: never;
    };
    "/journeys/{journeyId}/end": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                journeyId: components["parameters"]["JourneyID"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["endJourney"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/journeys/{journeyId}/convert-to-trip": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                journeyId: components["parameters"]["JourneyID"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["convertOutingToTrip"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/journeys/{journeyId}/locations/batch": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                journeyId: components["parameters"]["JourneyID"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["ingestLocations"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/journeys/{journeyId}/route": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                journeyId: components["parameters"]["JourneyID"];
            };
            cookie?: never;
        };
        get: operations["getJourneyRoute"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/journeys/{journeyId}/stops": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                journeyId: components["parameters"]["JourneyID"];
            };
            cookie?: never;
        };
        get: operations["listJourneyStops"];
        put?: never;
        post: operations["addJourneyStop"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/journeys/{journeyId}/stops/{stopId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["updateJourneyStopMetadata"];
        trace?: never;
    };
    "/places": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listPlaces"];
        put?: never;
        post: operations["savePlace"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/places/{placeId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                placeId: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["deletePlace"];
        options?: never;
        head?: never;
        patch: operations["updatePlace"];
        trace?: never;
    };
    "/places/nearby": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getNearbyPlaces"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/places/reverse-geocode": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["reverseGeocode"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/photos/upload-intents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["createPhotoUploadIntent"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/journeys/{journeyId}/stops/{stopId}/photos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listStopPhotos"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/photos/{photoId}/complete": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                photoId: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["completePhotoUpload"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/journeys/{journeyId}/shares": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                journeyId: components["parameters"]["JourneyID"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["createJourneyShare"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/shares/{token}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getPublicShare"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/share-links/{shareId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["revokeJourneyShare"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ErrorEnvelope: {
            error: {
                code: string;
                message: string;
                request_id: string;
            };
        };
        /**
         * @default motorcycle
         * @enum {string}
         */
        TransportMode: "motorcycle" | "car" | "walking";
        User: {
            /** Format: uuid */
            id: string;
            subject: string;
            display_name: string;
            default_transport_mode: components["schemas"]["TransportMode"];
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        UpdateProfileRequest: {
            display_name: string;
            default_transport_mode: components["schemas"]["TransportMode"];
        };
        RegisterDeviceRequest: {
            installation_id: string;
            /** @enum {string} */
            platform: "web" | "android";
            push_subscription?: {
                [key: string]: unknown;
            };
        };
        Device: {
            /** Format: uuid */
            id: string;
            installation_id: string;
            /** @enum {string} */
            platform: "web" | "android";
            /** Format: date-time */
            last_seen_at: string;
        };
        DeviceList: {
            items: components["schemas"]["Device"][];
        };
        /** @enum {string} */
        JourneyKind: "trip" | "outing";
        /** @enum {string} */
        JourneyStatus: "active" | "ended" | "expired";
        CreateJourneyRequest: {
            kind: components["schemas"]["JourneyKind"];
            label: string;
            /** Format: uuid */
            client_request_id: string;
        };
        UpdateJourneyRequest: {
            label: string;
            /** Format: int32 */
            version: number;
        };
        VersionRequest: {
            /** Format: int32 */
            version: number;
        };
        Journey: {
            /** Format: uuid */
            id: string;
            kind: components["schemas"]["JourneyKind"];
            label: string;
            status: components["schemas"]["JourneyStatus"];
            /** Format: date-time */
            started_at: string;
            /** Format: date-time */
            ended_at: string | null;
            /** Format: int32 */
            version: number;
        };
        JourneyList: {
            items: components["schemas"]["Journey"][];
        };
        SavePlaceRequest: {
            /** Format: uuid */
            client_request_id: string;
            name: string;
            notes?: string;
            /** Format: double */
            latitude: number;
            /** Format: double */
            longitude: number;
        };
        UpdatePlaceRequest: {
            name: string;
            notes: string;
        };
        Place: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            client_request_id: string;
            name: string;
            notes: string;
            /** Format: double */
            latitude: number;
            /** Format: double */
            longitude: number;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        PlaceList: {
            items: components["schemas"]["Place"][];
        };
        PinStopRequest: {
            /** Format: uuid */
            client_request_id: string;
            name: string;
            note?: string;
            /** Format: double */
            latitude: number;
            /** Format: double */
            longitude: number;
            /** Format: date-time */
            captured_at: string;
        };
        UpdateStopRequest: {
            name: string;
            note: string;
        };
        JourneyStop: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            journey_id: string;
            /** Format: uuid */
            place_id: string;
            /** Format: uuid */
            client_request_id: string;
            /** Format: int64 */
            sequence_number: number;
            /** Format: date-time */
            captured_at: string;
            name: string;
            note: string;
            /** Format: double */
            latitude: number;
            /** Format: double */
            longitude: number;
        };
        JourneyStopList: {
            items: components["schemas"]["JourneyStop"][];
        };
        LocationPoint: {
            /** Format: uuid */
            sample_id: string;
            /** Format: date-time */
            captured_at: string;
            /** Format: double */
            latitude: number;
            /** Format: double */
            longitude: number;
            /** Format: float */
            accuracy_m?: number | null;
            /** Format: float */
            speed_mps?: number | null;
            /** Format: float */
            heading_deg?: number | null;
        };
        LocationIngestResult: {
            received: number;
            inserted: number;
            duplicates: number;
            flagged: number;
        };
        GeoJSONLineString: {
            /** @enum {string} */
            type: "LineString";
            coordinates: number[][];
        };
        RouteSegment: {
            /** Format: uuid */
            id: string;
            /** Format: int32 */
            number: number;
            /** Format: date-time */
            started_at: string;
            /** Format: date-time */
            ended_at: string;
            geometry: components["schemas"]["GeoJSONLineString"];
            /** Format: double */
            distance_m: number;
            /** Format: int32 */
            duration_s: number;
            is_map_matched: boolean;
        };
        RouteSegmentList: {
            segments: components["schemas"]["RouteSegment"][];
        };
        RoadEstimate: {
            /** Format: double */
            distance_m: number;
            /** Format: int32 */
            duration_s: number;
        };
        NearbyRoutes: {
            motorcycle?: components["schemas"]["RoadEstimate"];
            car?: components["schemas"]["RoadEstimate"];
            walking?: components["schemas"]["RoadEstimate"];
        };
        NearbyPlace: {
            /** Format: uuid */
            place_id: string;
            name: string;
            /** Format: double */
            latitude: number;
            /** Format: double */
            longitude: number;
            /**
             * Format: double
             * @description Internal prefilter diagnostic; not the default displayed distance.
             */
            straight_line_m: number;
            routes: components["schemas"]["NearbyRoutes"];
        };
        NearbyResult: {
            sort_mode: components["schemas"]["TransportMode"];
            items: components["schemas"]["NearbyPlace"][];
        };
        ReverseGeocodeResult: {
            display_name: string;
        };
        /** @enum {string} */
        PhotoContentType: "image/jpeg" | "image/png" | "image/webp";
        CreatePhotoUploadIntentRequest: {
            /** Format: uuid */
            journey_id: string;
            /** Format: uuid */
            stop_id?: string | null;
            /** Format: uuid */
            client_request_id: string;
            content_type: components["schemas"]["PhotoContentType"];
            /** Format: date-time */
            captured_at?: string | null;
        };
        PhotoUploadIntent: {
            /** Format: uuid */
            photo_id: string;
            /** Format: uri */
            upload_url: string;
            /** @enum {string} */
            method: "PUT";
            /** Format: date-time */
            expires_at: string;
            /** Format: int64 */
            max_bytes: number;
            content_type: components["schemas"]["PhotoContentType"];
        };
        CompletePhotoUploadRequest: {
            checksum_sha256?: string;
        };
        PhotoProcessingStatus: {
            /** Format: uuid */
            photo_id: string;
            /** @enum {string} */
            status: "uploaded" | "processed";
        };
        Photo: {
            /** Format: uuid */
            photo_id: string;
            /** Format: uri */
            url: string;
            /** Format: date-time */
            captured_at: string | null;
        };
        PhotoList: {
            items: components["schemas"]["Photo"][];
        };
        ShareItemInput: {
            /** Format: uuid */
            stop_id: string;
            display_name?: string | null;
            note?: string | null;
            photo_ids?: string[];
        };
        CreateShareRequest: {
            title?: string;
            /** Format: date-time */
            expires_at?: string | null;
            /** @description Share-only order; omitting or passing an empty array uses the original timeline. */
            items?: components["schemas"]["ShareItemInput"][];
        };
        CreatedShare: {
            /** Format: uuid */
            id: string;
            /** Format: uri */
            url: string;
            message: string;
        };
        PublicPhoto: {
            /** Format: uuid */
            id: string;
            /** Format: uri */
            url: string;
        };
        PublicItineraryItem: {
            /** Format: uuid */
            stop_id: string;
            display_name: string;
            note: string;
            /** Format: double */
            latitude: number;
            /** Format: double */
            longitude: number;
            /** Format: date-time */
            captured_at: string;
            photos: components["schemas"]["PublicPhoto"][];
        };
        PublicItinerary: {
            title: string;
            /** Format: date-time */
            started_at: string;
            /** Format: date-time */
            ended_at: string | null;
            items: components["schemas"]["PublicItineraryItem"][];
        };
    };
    responses: {
        /** @description Error response */
        Error: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
    };
    parameters: {
        JourneyID: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current user and preferences */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    updateMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateProfileRequest"];
            };
        };
        responses: {
            /** @description Updated current user */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    listDevices: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Registered devices */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeviceList"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    registerDevice: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterDeviceRequest"];
            };
        };
        responses: {
            /** @description Device registered */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Device"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    deleteDevice: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                deviceId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Device removed */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: components["responses"]["Error"];
        };
    };
    listJourneys: {
        parameters: {
            query?: {
                before?: string;
                page_size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Journeys owned by the current user */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JourneyList"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    createJourney: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateJourneyRequest"];
            };
        };
        responses: {
            /** @description Journey created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Journey"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    getJourney: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                journeyId: components["parameters"]["JourneyID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Journey detail */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Journey"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    updateJourney: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                journeyId: components["parameters"]["JourneyID"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateJourneyRequest"];
            };
        };
        responses: {
            /** @description Journey updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Journey"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    endJourney: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                journeyId: components["parameters"]["JourneyID"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VersionRequest"];
            };
        };
        responses: {
            /** @description Journey ended */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Journey"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    convertOutingToTrip: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                journeyId: components["parameters"]["JourneyID"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VersionRequest"];
            };
        };
        responses: {
            /** @description Outing converted to trip */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Journey"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    ingestLocations: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                journeyId: components["parameters"]["JourneyID"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    points: components["schemas"]["LocationPoint"][];
                };
            };
        };
        responses: {
            /** @description Location samples accepted */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LocationIngestResult"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    getJourneyRoute: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                journeyId: components["parameters"]["JourneyID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Cleaned route segments, map-matched when available */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RouteSegmentList"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    listJourneyStops: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                journeyId: components["parameters"]["JourneyID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Original chronological stop timeline */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JourneyStopList"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    addJourneyStop: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                journeyId: components["parameters"]["JourneyID"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PinStopRequest"];
            };
        };
        responses: {
            /** @description Stop added to the immutable timeline */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JourneyStop"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    updateJourneyStopMetadata: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                journeyId: components["parameters"]["JourneyID"];
                stopId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateStopRequest"];
            };
        };
        responses: {
            /** @description Editable stop metadata updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JourneyStop"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    listPlaces: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Saved place library */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlaceList"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    savePlace: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SavePlaceRequest"];
            };
        };
        responses: {
            /** @description Place saved */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Place"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    deletePlace: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                placeId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Place removed from the library */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: components["responses"]["Error"];
        };
    };
    updatePlace: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                placeId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdatePlaceRequest"];
            };
        };
        responses: {
            /** @description Place metadata updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Place"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    getNearbyPlaces: {
        parameters: {
            query: {
                latitude: number;
                longitude: number;
                limit?: number;
                mode?: components["schemas"]["TransportMode"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Saved places ordered by road distance for the selected mode, with all available mode estimates */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NearbyResult"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    reverseGeocode: {
        parameters: {
            query: {
                latitude: number;
                longitude: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Suggested place label */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReverseGeocodeResult"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    createPhotoUploadIntent: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreatePhotoUploadIntentRequest"];
            };
        };
        responses: {
            /** @description Short-lived signed upload URL */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PhotoUploadIntent"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    listStopPhotos: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                journeyId: components["parameters"]["JourneyID"];
                stopId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Processed photos with short-lived private thumbnail URLs */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PhotoList"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    completePhotoUpload: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                photoId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CompletePhotoUploadRequest"];
            };
        };
        responses: {
            /** @description Upload recorded and processing queued */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PhotoProcessingStatus"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    createJourneyShare: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                journeyId: components["parameters"]["JourneyID"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateShareRequest"];
            };
        };
        responses: {
            /** @description Immutable public itinerary snapshot created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreatedShare"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    getPublicShare: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                token: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Public itinerary snapshot */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicItinerary"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    revokeJourneyShare: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                shareId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Share revoked */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: components["responses"]["Error"];
        };
    };
}
