// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: devices.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteDevice = `-- name: DeleteDevice :execrows
DELETE FROM devices WHERE id = $1 AND user_id = $2
`

type DeleteDeviceParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) DeleteDevice(ctx context.Context, arg DeleteDeviceParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteDevice, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listDevices = `-- name: ListDevices :many
SELECT id, user_id, installation_id, platform, push_subscription, last_seen_at, created_at, updated_at FROM devices
WHERE user_id = $1
ORDER BY last_seen_at DESC
`

func (q *Queries) ListDevices(ctx context.Context, userID pgtype.UUID) ([]Device, error) {
	rows, err := q.db.Query(ctx, listDevices, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Device{}
	for rows.Next() {
		var i Device
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.InstallationID,
			&i.Platform,
			&i.PushSubscription,
			&i.LastSeenAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertDevice = `-- name: UpsertDevice :one
INSERT INTO devices (user_id, installation_id, platform, push_subscription)
VALUES ($1, $2, $3, $4)
ON CONFLICT (user_id, installation_id) DO UPDATE
SET platform = EXCLUDED.platform,
    push_subscription = EXCLUDED.push_subscription,
    last_seen_at = now(),
    updated_at = now()
RETURNING id, user_id, installation_id, platform, push_subscription, last_seen_at, created_at, updated_at
`

type UpsertDeviceParams struct {
	UserID           pgtype.UUID `json:"user_id"`
	InstallationID   string      `json:"installation_id"`
	Platform         string      `json:"platform"`
	PushSubscription []byte      `json:"push_subscription"`
}

func (q *Queries) UpsertDevice(ctx context.Context, arg UpsertDeviceParams) (Device, error) {
	row := q.db.QueryRow(ctx, upsertDevice,
		arg.UserID,
		arg.InstallationID,
		arg.Platform,
		arg.PushSubscription,
	)
	var i Device
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.InstallationID,
		&i.Platform,
		&i.PushSubscription,
		&i.LastSeenAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
