// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: geocoding.sql

package dbgen

import (
	"context"
)

const getReverseGeocodeCache = `-- name: GetReverseGeocodeCache :one
SELECT latitude_e5, longitude_e5, display_name, provider_payload, created_at, updated_at FROM reverse_geocode_cache
WHERE latitude_e5 = $1 AND longitude_e5 = $2
`

type GetReverseGeocodeCacheParams struct {
	LatitudeE5  int32 `json:"latitude_e5"`
	LongitudeE5 int32 `json:"longitude_e5"`
}

func (q *Queries) GetReverseGeocodeCache(ctx context.Context, arg GetReverseGeocodeCacheParams) (ReverseGeocodeCache, error) {
	row := q.db.QueryRow(ctx, getReverseGeocodeCache, arg.LatitudeE5, arg.LongitudeE5)
	var i ReverseGeocodeCache
	err := row.Scan(
		&i.LatitudeE5,
		&i.LongitudeE5,
		&i.DisplayName,
		&i.ProviderPayload,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertReverseGeocodeCache = `-- name: UpsertReverseGeocodeCache :one
INSERT INTO reverse_geocode_cache (latitude_e5, longitude_e5, display_name, provider_payload)
VALUES ($1, $2, $3, $4)
ON CONFLICT (latitude_e5, longitude_e5) DO UPDATE
SET display_name = EXCLUDED.display_name,
    provider_payload = EXCLUDED.provider_payload,
    updated_at = now()
RETURNING latitude_e5, longitude_e5, display_name, provider_payload, created_at, updated_at
`

type UpsertReverseGeocodeCacheParams struct {
	LatitudeE5      int32  `json:"latitude_e5"`
	LongitudeE5     int32  `json:"longitude_e5"`
	DisplayName     string `json:"display_name"`
	ProviderPayload []byte `json:"provider_payload"`
}

func (q *Queries) UpsertReverseGeocodeCache(ctx context.Context, arg UpsertReverseGeocodeCacheParams) (ReverseGeocodeCache, error) {
	row := q.db.QueryRow(ctx, upsertReverseGeocodeCache,
		arg.LatitudeE5,
		arg.LongitudeE5,
		arg.DisplayName,
		arg.ProviderPayload,
	)
	var i ReverseGeocodeCache
	err := row.Scan(
		&i.LatitudeE5,
		&i.LongitudeE5,
		&i.DisplayName,
		&i.ProviderPayload,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
