// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: geocoding.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getPlaceSearchCache = `-- name: GetPlaceSearchCache :one
SELECT cache_key, results, result_count, expires_at, created_at, updated_at FROM place_search_cache
WHERE cache_key = $1
  AND expires_at > now()
`

func (q *Queries) GetPlaceSearchCache(ctx context.Context, cacheKey string) (PlaceSearchCache, error) {
	row := q.db.QueryRow(ctx, getPlaceSearchCache, cacheKey)
	var i PlaceSearchCache
	err := row.Scan(
		&i.CacheKey,
		&i.Results,
		&i.ResultCount,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getReverseGeocodeCache = `-- name: GetReverseGeocodeCache :one
SELECT latitude_e5, longitude_e5, display_name, provider_payload, created_at, updated_at FROM reverse_geocode_cache
WHERE latitude_e5 = $1 AND longitude_e5 = $2
`

type GetReverseGeocodeCacheParams struct {
	LatitudeE5  int32 `json:"latitude_e5"`
	LongitudeE5 int32 `json:"longitude_e5"`
}

func (q *Queries) GetReverseGeocodeCache(ctx context.Context, arg GetReverseGeocodeCacheParams) (ReverseGeocodeCache, error) {
	row := q.db.QueryRow(ctx, getReverseGeocodeCache, arg.LatitudeE5, arg.LongitudeE5)
	var i ReverseGeocodeCache
	err := row.Scan(
		&i.LatitudeE5,
		&i.LongitudeE5,
		&i.DisplayName,
		&i.ProviderPayload,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const reserveProviderDailyUsage = `-- name: ReserveProviderDailyUsage :one
INSERT INTO provider_daily_usage (provider, usage_date, request_count)
VALUES ($1, (now() AT TIME ZONE 'UTC')::date, 1)
ON CONFLICT (provider, usage_date) DO UPDATE
SET request_count = provider_daily_usage.request_count + 1,
    updated_at = now()
WHERE provider_daily_usage.request_count < $2
RETURNING provider, usage_date, request_count, updated_at
`

type ReserveProviderDailyUsageParams struct {
	Provider   string `json:"provider"`
	DailyLimit int32  `json:"daily_limit"`
}

func (q *Queries) ReserveProviderDailyUsage(ctx context.Context, arg ReserveProviderDailyUsageParams) (ProviderDailyUsage, error) {
	row := q.db.QueryRow(ctx, reserveProviderDailyUsage, arg.Provider, arg.DailyLimit)
	var i ProviderDailyUsage
	err := row.Scan(
		&i.Provider,
		&i.UsageDate,
		&i.RequestCount,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertPlaceSearchCache = `-- name: UpsertPlaceSearchCache :one
INSERT INTO place_search_cache (cache_key, results, result_count, expires_at)
VALUES ($1, $2, $3, $4)
ON CONFLICT (cache_key) DO UPDATE
SET results = EXCLUDED.results,
    result_count = EXCLUDED.result_count,
    expires_at = EXCLUDED.expires_at,
    updated_at = now()
RETURNING cache_key, results, result_count, expires_at, created_at, updated_at
`

type UpsertPlaceSearchCacheParams struct {
	CacheKey    string             `json:"cache_key"`
	Results     []byte             `json:"results"`
	ResultCount int32              `json:"result_count"`
	ExpiresAt   pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) UpsertPlaceSearchCache(ctx context.Context, arg UpsertPlaceSearchCacheParams) (PlaceSearchCache, error) {
	row := q.db.QueryRow(ctx, upsertPlaceSearchCache,
		arg.CacheKey,
		arg.Results,
		arg.ResultCount,
		arg.ExpiresAt,
	)
	var i PlaceSearchCache
	err := row.Scan(
		&i.CacheKey,
		&i.Results,
		&i.ResultCount,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertReverseGeocodeCache = `-- name: UpsertReverseGeocodeCache :one
INSERT INTO reverse_geocode_cache (latitude_e5, longitude_e5, display_name, provider_payload)
VALUES ($1, $2, $3, $4)
ON CONFLICT (latitude_e5, longitude_e5) DO UPDATE
SET display_name = EXCLUDED.display_name,
    provider_payload = EXCLUDED.provider_payload,
    updated_at = now()
RETURNING latitude_e5, longitude_e5, display_name, provider_payload, created_at, updated_at
`

type UpsertReverseGeocodeCacheParams struct {
	LatitudeE5      int32  `json:"latitude_e5"`
	LongitudeE5     int32  `json:"longitude_e5"`
	DisplayName     string `json:"display_name"`
	ProviderPayload []byte `json:"provider_payload"`
}

func (q *Queries) UpsertReverseGeocodeCache(ctx context.Context, arg UpsertReverseGeocodeCacheParams) (ReverseGeocodeCache, error) {
	row := q.db.QueryRow(ctx, upsertReverseGeocodeCache,
		arg.LatitudeE5,
		arg.LongitudeE5,
		arg.DisplayName,
		arg.ProviderPayload,
	)
	var i ReverseGeocodeCache
	err := row.Scan(
		&i.LatitudeE5,
		&i.LongitudeE5,
		&i.DisplayName,
		&i.ProviderPayload,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
