// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: jobs.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addOutboxEvent = `-- name: AddOutboxEvent :one
INSERT INTO outbox_events (aggregate_type, aggregate_id, event_type, payload)
VALUES ($1, $2, $3, $4)
RETURNING id, aggregate_type, aggregate_id, event_type, payload, created_at, published_at
`

type AddOutboxEventParams struct {
	AggregateType string      `json:"aggregate_type"`
	AggregateID   pgtype.UUID `json:"aggregate_id"`
	EventType     string      `json:"event_type"`
	Payload       []byte      `json:"payload"`
}

func (q *Queries) AddOutboxEvent(ctx context.Context, arg AddOutboxEventParams) (OutboxEvent, error) {
	row := q.db.QueryRow(ctx, addOutboxEvent,
		arg.AggregateType,
		arg.AggregateID,
		arg.EventType,
		arg.Payload,
	)
	var i OutboxEvent
	err := row.Scan(
		&i.ID,
		&i.AggregateType,
		&i.AggregateID,
		&i.EventType,
		&i.Payload,
		&i.CreatedAt,
		&i.PublishedAt,
	)
	return i, err
}

const claimNextJobs = `-- name: ClaimNextJobs :many
WITH next_jobs AS (
    SELECT id
    FROM background_jobs
    WHERE state = 'available' AND run_at <= now()
    ORDER BY run_at, id
    LIMIT $2
    FOR UPDATE SKIP LOCKED
)
UPDATE background_jobs AS jobs
SET state = 'running',
    attempts = attempts + 1,
    locked_at = now(),
    locked_by = $1,
    updated_at = now()
FROM next_jobs
WHERE jobs.id = next_jobs.id
RETURNING jobs.id, jobs.job_type, jobs.payload, jobs.idempotency_key, jobs.state, jobs.attempts, jobs.max_attempts, jobs.run_at, jobs.locked_at, jobs.locked_by, jobs.last_error, jobs.created_at, jobs.updated_at
`

type ClaimNextJobsParams struct {
	WorkerID  pgtype.Text `json:"worker_id"`
	BatchSize int32       `json:"batch_size"`
}

func (q *Queries) ClaimNextJobs(ctx context.Context, arg ClaimNextJobsParams) ([]BackgroundJob, error) {
	rows, err := q.db.Query(ctx, claimNextJobs, arg.WorkerID, arg.BatchSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BackgroundJob{}
	for rows.Next() {
		var i BackgroundJob
		if err := rows.Scan(
			&i.ID,
			&i.JobType,
			&i.Payload,
			&i.IdempotencyKey,
			&i.State,
			&i.Attempts,
			&i.MaxAttempts,
			&i.RunAt,
			&i.LockedAt,
			&i.LockedBy,
			&i.LastError,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const completeJob = `-- name: CompleteJob :exec
DELETE FROM background_jobs
WHERE id = $1 AND state = 'running'
`

func (q *Queries) CompleteJob(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, completeJob, id)
	return err
}

const enqueueJob = `-- name: EnqueueJob :one
INSERT INTO background_jobs (job_type, payload, idempotency_key, max_attempts, run_at)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (job_type, idempotency_key) WHERE idempotency_key IS NOT NULL
DO UPDATE SET updated_at = background_jobs.updated_at
RETURNING id, job_type, payload, idempotency_key, state, attempts, max_attempts, run_at, locked_at, locked_by, last_error, created_at, updated_at
`

type EnqueueJobParams struct {
	JobType        string             `json:"job_type"`
	Payload        []byte             `json:"payload"`
	IdempotencyKey pgtype.Text        `json:"idempotency_key"`
	MaxAttempts    int32              `json:"max_attempts"`
	RunAt          pgtype.Timestamptz `json:"run_at"`
}

func (q *Queries) EnqueueJob(ctx context.Context, arg EnqueueJobParams) (BackgroundJob, error) {
	row := q.db.QueryRow(ctx, enqueueJob,
		arg.JobType,
		arg.Payload,
		arg.IdempotencyKey,
		arg.MaxAttempts,
		arg.RunAt,
	)
	var i BackgroundJob
	err := row.Scan(
		&i.ID,
		&i.JobType,
		&i.Payload,
		&i.IdempotencyKey,
		&i.State,
		&i.Attempts,
		&i.MaxAttempts,
		&i.RunAt,
		&i.LockedAt,
		&i.LockedBy,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listUnpublishedEvents = `-- name: ListUnpublishedEvents :many
SELECT id, aggregate_type, aggregate_id, event_type, payload, created_at, published_at FROM outbox_events
WHERE published_at IS NULL
ORDER BY id
LIMIT $1
`

func (q *Queries) ListUnpublishedEvents(ctx context.Context, limit int32) ([]OutboxEvent, error) {
	rows, err := q.db.Query(ctx, listUnpublishedEvents, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OutboxEvent{}
	for rows.Next() {
		var i OutboxEvent
		if err := rows.Scan(
			&i.ID,
			&i.AggregateType,
			&i.AggregateID,
			&i.EventType,
			&i.Payload,
			&i.CreatedAt,
			&i.PublishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markOutboxEventPublished = `-- name: MarkOutboxEventPublished :exec
UPDATE outbox_events SET published_at = now() WHERE id = $1
`

func (q *Queries) MarkOutboxEventPublished(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, markOutboxEventPublished, id)
	return err
}

const requeueStaleJobs = `-- name: RequeueStaleJobs :execrows
UPDATE background_jobs
SET state = 'available',
    locked_at = NULL,
    locked_by = NULL,
    run_at = now(),
    updated_at = now()
WHERE state = 'running' AND locked_at < $1
`

func (q *Queries) RequeueStaleJobs(ctx context.Context, lockedAt pgtype.Timestamptz) (int64, error) {
	result, err := q.db.Exec(ctx, requeueStaleJobs, lockedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const retryJob = `-- name: RetryJob :exec
UPDATE background_jobs
SET state = CASE WHEN attempts >= max_attempts THEN 'dead' ELSE 'available' END,
    run_at = CASE WHEN attempts >= max_attempts THEN run_at ELSE $2 END,
    locked_at = NULL,
    locked_by = NULL,
    last_error = $3,
    updated_at = now()
WHERE id = $1 AND state = 'running'
`

type RetryJobParams struct {
	ID        int64              `json:"id"`
	RunAt     pgtype.Timestamptz `json:"run_at"`
	LastError pgtype.Text        `json:"last_error"`
}

func (q *Queries) RetryJob(ctx context.Context, arg RetryJobParams) error {
	_, err := q.db.Exec(ctx, retryJob, arg.ID, arg.RunAt, arg.LastError)
	return err
}
