// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: journeys.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const completeJourney = `-- name: CompleteJourney :one
UPDATE journeys
SET status = 'ended', ended_at = $3, version = version + 1, updated_at = now()
WHERE id = $1 AND owner_id = $2 AND status = 'active' AND version = $4
RETURNING id, owner_id, client_request_id, kind, label, status, started_at, ended_at, version, created_at, updated_at
`

type CompleteJourneyParams struct {
	ID      pgtype.UUID        `json:"id"`
	OwnerID pgtype.UUID        `json:"owner_id"`
	EndedAt pgtype.Timestamptz `json:"ended_at"`
	Version int32              `json:"version"`
}

func (q *Queries) CompleteJourney(ctx context.Context, arg CompleteJourneyParams) (Journey, error) {
	row := q.db.QueryRow(ctx, completeJourney,
		arg.ID,
		arg.OwnerID,
		arg.EndedAt,
		arg.Version,
	)
	var i Journey
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.ClientRequestID,
		&i.Kind,
		&i.Label,
		&i.Status,
		&i.StartedAt,
		&i.EndedAt,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const convertOutingToTrip = `-- name: ConvertOutingToTrip :one
UPDATE journeys
SET kind = 'trip', version = version + 1, updated_at = now()
WHERE id = $1 AND owner_id = $2 AND kind = 'outing' AND status = 'active' AND version = $3
RETURNING id, owner_id, client_request_id, kind, label, status, started_at, ended_at, version, created_at, updated_at
`

type ConvertOutingToTripParams struct {
	ID      pgtype.UUID `json:"id"`
	OwnerID pgtype.UUID `json:"owner_id"`
	Version int32       `json:"version"`
}

func (q *Queries) ConvertOutingToTrip(ctx context.Context, arg ConvertOutingToTripParams) (Journey, error) {
	row := q.db.QueryRow(ctx, convertOutingToTrip, arg.ID, arg.OwnerID, arg.Version)
	var i Journey
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.ClientRequestID,
		&i.Kind,
		&i.Label,
		&i.Status,
		&i.StartedAt,
		&i.EndedAt,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createJourney = `-- name: CreateJourney :one
INSERT INTO journeys (owner_id, client_request_id, kind, label, started_at)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (owner_id, client_request_id) DO UPDATE
SET client_request_id = journeys.client_request_id
RETURNING id, owner_id, client_request_id, kind, label, status, started_at, ended_at, version, created_at, updated_at
`

type CreateJourneyParams struct {
	OwnerID         pgtype.UUID        `json:"owner_id"`
	ClientRequestID pgtype.UUID        `json:"client_request_id"`
	Kind            string             `json:"kind"`
	Label           string             `json:"label"`
	StartedAt       pgtype.Timestamptz `json:"started_at"`
}

func (q *Queries) CreateJourney(ctx context.Context, arg CreateJourneyParams) (Journey, error) {
	row := q.db.QueryRow(ctx, createJourney,
		arg.OwnerID,
		arg.ClientRequestID,
		arg.Kind,
		arg.Label,
		arg.StartedAt,
	)
	var i Journey
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.ClientRequestID,
		&i.Kind,
		&i.Label,
		&i.Status,
		&i.StartedAt,
		&i.EndedAt,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const expireJourney = `-- name: ExpireJourney :one
UPDATE journeys
SET status = 'expired', ended_at = $2, version = version + 1, updated_at = now()
WHERE id = $1 AND status = 'active'
RETURNING id, owner_id, client_request_id, kind, label, status, started_at, ended_at, version, created_at, updated_at
`

type ExpireJourneyParams struct {
	ID      pgtype.UUID        `json:"id"`
	EndedAt pgtype.Timestamptz `json:"ended_at"`
}

func (q *Queries) ExpireJourney(ctx context.Context, arg ExpireJourneyParams) (Journey, error) {
	row := q.db.QueryRow(ctx, expireJourney, arg.ID, arg.EndedAt)
	var i Journey
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.ClientRequestID,
		&i.Kind,
		&i.Label,
		&i.Status,
		&i.StartedAt,
		&i.EndedAt,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getJourney = `-- name: GetJourney :one
SELECT id, owner_id, client_request_id, kind, label, status, started_at, ended_at, version, created_at, updated_at FROM journeys WHERE id = $1 AND owner_id = $2
`

type GetJourneyParams struct {
	ID      pgtype.UUID `json:"id"`
	OwnerID pgtype.UUID `json:"owner_id"`
}

func (q *Queries) GetJourney(ctx context.Context, arg GetJourneyParams) (Journey, error) {
	row := q.db.QueryRow(ctx, getJourney, arg.ID, arg.OwnerID)
	var i Journey
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.ClientRequestID,
		&i.Kind,
		&i.Label,
		&i.Status,
		&i.StartedAt,
		&i.EndedAt,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listActiveOutingsBefore = `-- name: ListActiveOutingsBefore :many
SELECT id, owner_id, client_request_id, kind, label, status, started_at, ended_at, version, created_at, updated_at FROM journeys
WHERE kind = 'outing' AND status = 'active' AND started_at <= $1
ORDER BY started_at
LIMIT $2
`

type ListActiveOutingsBeforeParams struct {
	StartedAt pgtype.Timestamptz `json:"started_at"`
	Limit     int32              `json:"limit"`
}

func (q *Queries) ListActiveOutingsBefore(ctx context.Context, arg ListActiveOutingsBeforeParams) ([]Journey, error) {
	rows, err := q.db.Query(ctx, listActiveOutingsBefore, arg.StartedAt, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Journey{}
	for rows.Next() {
		var i Journey
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.ClientRequestID,
			&i.Kind,
			&i.Label,
			&i.Status,
			&i.StartedAt,
			&i.EndedAt,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listJourneys = `-- name: ListJourneys :many
SELECT id, owner_id, client_request_id, kind, label, status, started_at, ended_at, version, created_at, updated_at FROM journeys
WHERE owner_id = $1
  AND ($2::timestamptz IS NULL OR started_at < $2)
ORDER BY started_at DESC, id DESC
LIMIT $3
`

type ListJourneysParams struct {
	OwnerID         pgtype.UUID        `json:"owner_id"`
	BeforeStartedAt pgtype.Timestamptz `json:"before_started_at"`
	PageSize        int32              `json:"page_size"`
}

func (q *Queries) ListJourneys(ctx context.Context, arg ListJourneysParams) ([]Journey, error) {
	rows, err := q.db.Query(ctx, listJourneys, arg.OwnerID, arg.BeforeStartedAt, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Journey{}
	for rows.Next() {
		var i Journey
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.ClientRequestID,
			&i.Kind,
			&i.Label,
			&i.Status,
			&i.StartedAt,
			&i.EndedAt,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateJourneyLabel = `-- name: UpdateJourneyLabel :one
UPDATE journeys
SET label = $3, version = version + 1, updated_at = now()
WHERE id = $1 AND owner_id = $2 AND version = $4
RETURNING id, owner_id, client_request_id, kind, label, status, started_at, ended_at, version, created_at, updated_at
`

type UpdateJourneyLabelParams struct {
	ID      pgtype.UUID `json:"id"`
	OwnerID pgtype.UUID `json:"owner_id"`
	Label   string      `json:"label"`
	Version int32       `json:"version"`
}

func (q *Queries) UpdateJourneyLabel(ctx context.Context, arg UpdateJourneyLabelParams) (Journey, error) {
	row := q.db.QueryRow(ctx, updateJourneyLabel,
		arg.ID,
		arg.OwnerID,
		arg.Label,
		arg.Version,
	)
	var i Journey
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.ClientRequestID,
		&i.Kind,
		&i.Label,
		&i.Status,
		&i.StartedAt,
		&i.EndedAt,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
