// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: nearby.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const nearbyPlaceCandidates = `-- name: NearbyPlaceCandidates :many
WITH origin AS (
    SELECT ST_SetSRID(ST_MakePoint(
        $4::double precision,
        $5::double precision
    ), 4326)::geography AS location
)
SELECT places.id, places.name,
    ST_Y(places.location::geometry)::double precision AS latitude,
    ST_X(places.location::geometry)::double precision AS longitude,
    ST_Distance(places.location, origin.location)::double precision AS straight_line_m
FROM places
CROSS JOIN origin
WHERE places.owner_id = $1
  AND places.deleted_at IS NULL
  AND ST_DWithin(places.location, origin.location, $2::double precision)
ORDER BY ST_Distance(places.location, origin.location), places.id
LIMIT $3
`

type NearbyPlaceCandidatesParams struct {
	OwnerID        pgtype.UUID `json:"owner_id"`
	RadiusM        float64     `json:"radius_m"`
	CandidateLimit int32       `json:"candidate_limit"`
	Longitude      float64     `json:"longitude"`
	Latitude       float64     `json:"latitude"`
}

type NearbyPlaceCandidatesRow struct {
	ID            pgtype.UUID `json:"id"`
	Name          string      `json:"name"`
	Latitude      float64     `json:"latitude"`
	Longitude     float64     `json:"longitude"`
	StraightLineM float64     `json:"straight_line_m"`
}

func (q *Queries) NearbyPlaceCandidates(ctx context.Context, arg NearbyPlaceCandidatesParams) ([]NearbyPlaceCandidatesRow, error) {
	rows, err := q.db.Query(ctx, nearbyPlaceCandidates,
		arg.OwnerID,
		arg.RadiusM,
		arg.CandidateLimit,
		arg.Longitude,
		arg.Latitude,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []NearbyPlaceCandidatesRow{}
	for rows.Next() {
		var i NearbyPlaceCandidatesRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Latitude,
			&i.Longitude,
			&i.StraightLineM,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
