// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: notifications.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const clearDevicePushSubscription = `-- name: ClearDevicePushSubscription :exec
UPDATE devices SET push_subscription = NULL, updated_at = now() WHERE id = $1
`

func (q *Queries) ClearDevicePushSubscription(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, clearDevicePushSubscription, id)
	return err
}

const getJourneyByID = `-- name: GetJourneyByID :one
SELECT id, owner_id, client_request_id, kind, label, status, started_at, ended_at, version, created_at, updated_at FROM journeys WHERE id = $1
`

func (q *Queries) GetJourneyByID(ctx context.Context, id pgtype.UUID) (Journey, error) {
	row := q.db.QueryRow(ctx, getJourneyByID, id)
	var i Journey
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.ClientRequestID,
		&i.Kind,
		&i.Label,
		&i.Status,
		&i.StartedAt,
		&i.EndedAt,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listPushSubscriptionsForUser = `-- name: ListPushSubscriptionsForUser :many
SELECT id, push_subscription
FROM devices
WHERE user_id = $1 AND push_subscription IS NOT NULL
`

type ListPushSubscriptionsForUserRow struct {
	ID               pgtype.UUID `json:"id"`
	PushSubscription []byte      `json:"push_subscription"`
}

func (q *Queries) ListPushSubscriptionsForUser(ctx context.Context, userID pgtype.UUID) ([]ListPushSubscriptionsForUserRow, error) {
	rows, err := q.db.Query(ctx, listPushSubscriptionsForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPushSubscriptionsForUserRow{}
	for rows.Next() {
		var i ListPushSubscriptionsForUserRow
		if err := rows.Scan(&i.ID, &i.PushSubscription); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
