// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: photos.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const completePhotoUpload = `-- name: CompletePhotoUpload :one
UPDATE photos
SET status = 'uploaded', byte_size = $3, checksum_sha256 = $4, updated_at = now()
WHERE id = $1 AND owner_id = $2 AND status IN ('pending', 'uploaded')
RETURNING id, owner_id, journey_id, stop_id, object_key, thumbnail_key, content_type, byte_size, status, captured_at, created_at, updated_at, client_request_id, checksum_sha256
`

type CompletePhotoUploadParams struct {
	ID             pgtype.UUID `json:"id"`
	OwnerID        pgtype.UUID `json:"owner_id"`
	ByteSize       pgtype.Int8 `json:"byte_size"`
	ChecksumSha256 pgtype.Text `json:"checksum_sha256"`
}

func (q *Queries) CompletePhotoUpload(ctx context.Context, arg CompletePhotoUploadParams) (Photo, error) {
	row := q.db.QueryRow(ctx, completePhotoUpload,
		arg.ID,
		arg.OwnerID,
		arg.ByteSize,
		arg.ChecksumSha256,
	)
	var i Photo
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.JourneyID,
		&i.StopID,
		&i.ObjectKey,
		&i.ThumbnailKey,
		&i.ContentType,
		&i.ByteSize,
		&i.Status,
		&i.CapturedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ClientRequestID,
		&i.ChecksumSha256,
	)
	return i, err
}

const createPhotoUpload = `-- name: CreatePhotoUpload :one
INSERT INTO photos (
    id, owner_id, journey_id, stop_id, client_request_id, object_key,
    content_type, status, captured_at
)
SELECT $1, $2, journeys.id, $3,
    $4, $5, $6,
    'pending', $7
FROM journeys
WHERE journeys.id = $8 AND journeys.owner_id = $2
  AND ($3::uuid IS NULL OR EXISTS (
      SELECT 1 FROM journey_stops
      WHERE journey_stops.id = $3 AND journey_stops.journey_id = journeys.id
  ))
ON CONFLICT (owner_id, client_request_id) WHERE client_request_id IS NOT NULL
DO UPDATE SET client_request_id = photos.client_request_id
RETURNING id, owner_id, journey_id, stop_id, object_key, thumbnail_key, content_type, byte_size, status, captured_at, created_at, updated_at, client_request_id, checksum_sha256
`

type CreatePhotoUploadParams struct {
	ID              pgtype.UUID        `json:"id"`
	OwnerID         pgtype.UUID        `json:"owner_id"`
	StopID          pgtype.UUID        `json:"stop_id"`
	ClientRequestID pgtype.UUID        `json:"client_request_id"`
	ObjectKey       string             `json:"object_key"`
	ContentType     string             `json:"content_type"`
	CapturedAt      pgtype.Timestamptz `json:"captured_at"`
	JourneyID       pgtype.UUID        `json:"journey_id"`
}

func (q *Queries) CreatePhotoUpload(ctx context.Context, arg CreatePhotoUploadParams) (Photo, error) {
	row := q.db.QueryRow(ctx, createPhotoUpload,
		arg.ID,
		arg.OwnerID,
		arg.StopID,
		arg.ClientRequestID,
		arg.ObjectKey,
		arg.ContentType,
		arg.CapturedAt,
		arg.JourneyID,
	)
	var i Photo
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.JourneyID,
		&i.StopID,
		&i.ObjectKey,
		&i.ThumbnailKey,
		&i.ContentType,
		&i.ByteSize,
		&i.Status,
		&i.CapturedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ClientRequestID,
		&i.ChecksumSha256,
	)
	return i, err
}

const getPhotoForOwner = `-- name: GetPhotoForOwner :one
SELECT id, owner_id, journey_id, stop_id, object_key, thumbnail_key, content_type, byte_size, status, captured_at, created_at, updated_at, client_request_id, checksum_sha256 FROM photos WHERE id = $1 AND owner_id = $2
`

type GetPhotoForOwnerParams struct {
	ID      pgtype.UUID `json:"id"`
	OwnerID pgtype.UUID `json:"owner_id"`
}

func (q *Queries) GetPhotoForOwner(ctx context.Context, arg GetPhotoForOwnerParams) (Photo, error) {
	row := q.db.QueryRow(ctx, getPhotoForOwner, arg.ID, arg.OwnerID)
	var i Photo
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.JourneyID,
		&i.StopID,
		&i.ObjectKey,
		&i.ThumbnailKey,
		&i.ContentType,
		&i.ByteSize,
		&i.Status,
		&i.CapturedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ClientRequestID,
		&i.ChecksumSha256,
	)
	return i, err
}

const listStopPhotos = `-- name: ListStopPhotos :many
SELECT id, owner_id, journey_id, stop_id, object_key, thumbnail_key, content_type, byte_size, status, captured_at, created_at, updated_at, client_request_id, checksum_sha256 FROM photos
WHERE owner_id = $1 AND stop_id = $2 AND status = 'processed'
ORDER BY captured_at NULLS LAST, created_at
`

type ListStopPhotosParams struct {
	OwnerID pgtype.UUID `json:"owner_id"`
	StopID  pgtype.UUID `json:"stop_id"`
}

func (q *Queries) ListStopPhotos(ctx context.Context, arg ListStopPhotosParams) ([]Photo, error) {
	rows, err := q.db.Query(ctx, listStopPhotos, arg.OwnerID, arg.StopID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Photo{}
	for rows.Next() {
		var i Photo
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.JourneyID,
			&i.StopID,
			&i.ObjectKey,
			&i.ThumbnailKey,
			&i.ContentType,
			&i.ByteSize,
			&i.Status,
			&i.CapturedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ClientRequestID,
			&i.ChecksumSha256,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markPhotoFailed = `-- name: MarkPhotoFailed :exec
UPDATE photos SET status = 'failed', updated_at = now() WHERE id = $1
`

func (q *Queries) MarkPhotoFailed(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, markPhotoFailed, id)
	return err
}

const markPhotoProcessed = `-- name: MarkPhotoProcessed :one
UPDATE photos
SET status = 'processed', thumbnail_key = $2, updated_at = now()
WHERE id = $1 AND status IN ('uploaded', 'processed')
RETURNING id, owner_id, journey_id, stop_id, object_key, thumbnail_key, content_type, byte_size, status, captured_at, created_at, updated_at, client_request_id, checksum_sha256
`

type MarkPhotoProcessedParams struct {
	ID           pgtype.UUID `json:"id"`
	ThumbnailKey pgtype.Text `json:"thumbnail_key"`
}

func (q *Queries) MarkPhotoProcessed(ctx context.Context, arg MarkPhotoProcessedParams) (Photo, error) {
	row := q.db.QueryRow(ctx, markPhotoProcessed, arg.ID, arg.ThumbnailKey)
	var i Photo
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.JourneyID,
		&i.StopID,
		&i.ObjectKey,
		&i.ThumbnailKey,
		&i.ContentType,
		&i.ByteSize,
		&i.Status,
		&i.CapturedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ClientRequestID,
		&i.ChecksumSha256,
	)
	return i, err
}
