// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: places.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createJourneyStop = `-- name: CreateJourneyStop :one
INSERT INTO journey_stops (
    journey_id, place_id, client_request_id, sequence_number, captured_at,
    display_name, note, location
)
SELECT $1, places.id, $2, $3,
    $4, $5, $6, places.location
FROM places
WHERE places.id = $7 AND places.owner_id = $8 AND places.deleted_at IS NULL
ON CONFLICT (journey_id, client_request_id) WHERE client_request_id IS NOT NULL
DO UPDATE SET client_request_id = journey_stops.client_request_id
RETURNING id, journey_id, place_id, client_request_id, sequence_number, captured_at,
    display_name, note,
    ST_Y(location::geometry)::double precision AS latitude,
    ST_X(location::geometry)::double precision AS longitude,
    created_at, updated_at
`

type CreateJourneyStopParams struct {
	JourneyID       pgtype.UUID        `json:"journey_id"`
	ClientRequestID pgtype.UUID        `json:"client_request_id"`
	SequenceNumber  int64              `json:"sequence_number"`
	CapturedAt      pgtype.Timestamptz `json:"captured_at"`
	DisplayName     string             `json:"display_name"`
	Note            string             `json:"note"`
	PlaceID         pgtype.UUID        `json:"place_id"`
	OwnerID         pgtype.UUID        `json:"owner_id"`
}

type CreateJourneyStopRow struct {
	ID              pgtype.UUID        `json:"id"`
	JourneyID       pgtype.UUID        `json:"journey_id"`
	PlaceID         pgtype.UUID        `json:"place_id"`
	ClientRequestID pgtype.UUID        `json:"client_request_id"`
	SequenceNumber  int64              `json:"sequence_number"`
	CapturedAt      pgtype.Timestamptz `json:"captured_at"`
	DisplayName     string             `json:"display_name"`
	Note            string             `json:"note"`
	Latitude        float64            `json:"latitude"`
	Longitude       float64            `json:"longitude"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CreateJourneyStop(ctx context.Context, arg CreateJourneyStopParams) (CreateJourneyStopRow, error) {
	row := q.db.QueryRow(ctx, createJourneyStop,
		arg.JourneyID,
		arg.ClientRequestID,
		arg.SequenceNumber,
		arg.CapturedAt,
		arg.DisplayName,
		arg.Note,
		arg.PlaceID,
		arg.OwnerID,
	)
	var i CreateJourneyStopRow
	err := row.Scan(
		&i.ID,
		&i.JourneyID,
		&i.PlaceID,
		&i.ClientRequestID,
		&i.SequenceNumber,
		&i.CapturedAt,
		&i.DisplayName,
		&i.Note,
		&i.Latitude,
		&i.Longitude,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createPlace = `-- name: CreatePlace :one
INSERT INTO places (owner_id, client_request_id, name, notes, location)
VALUES ($1, $2, $3, $4, ST_SetSRID(ST_MakePoint(
    $5::double precision,
    $6::double precision
), 4326)::geography)
ON CONFLICT (owner_id, client_request_id) WHERE client_request_id IS NOT NULL
DO UPDATE SET client_request_id = places.client_request_id
RETURNING id, owner_id, client_request_id, name, notes,
    ST_Y(location::geometry)::double precision AS latitude,
    ST_X(location::geometry)::double precision AS longitude,
    created_at, updated_at
`

type CreatePlaceParams struct {
	OwnerID         pgtype.UUID `json:"owner_id"`
	ClientRequestID pgtype.UUID `json:"client_request_id"`
	Name            string      `json:"name"`
	Notes           string      `json:"notes"`
	Longitude       float64     `json:"longitude"`
	Latitude        float64     `json:"latitude"`
}

type CreatePlaceRow struct {
	ID              pgtype.UUID        `json:"id"`
	OwnerID         pgtype.UUID        `json:"owner_id"`
	ClientRequestID pgtype.UUID        `json:"client_request_id"`
	Name            string             `json:"name"`
	Notes           string             `json:"notes"`
	Latitude        float64            `json:"latitude"`
	Longitude       float64            `json:"longitude"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CreatePlace(ctx context.Context, arg CreatePlaceParams) (CreatePlaceRow, error) {
	row := q.db.QueryRow(ctx, createPlace,
		arg.OwnerID,
		arg.ClientRequestID,
		arg.Name,
		arg.Notes,
		arg.Longitude,
		arg.Latitude,
	)
	var i CreatePlaceRow
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.ClientRequestID,
		&i.Name,
		&i.Notes,
		&i.Latitude,
		&i.Longitude,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deletePlace = `-- name: DeletePlace :execrows
UPDATE places SET deleted_at = now(), updated_at = now()
WHERE id = $1 AND owner_id = $2 AND deleted_at IS NULL
`

type DeletePlaceParams struct {
	ID      pgtype.UUID `json:"id"`
	OwnerID pgtype.UUID `json:"owner_id"`
}

func (q *Queries) DeletePlace(ctx context.Context, arg DeletePlaceParams) (int64, error) {
	result, err := q.db.Exec(ctx, deletePlace, arg.ID, arg.OwnerID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getJourneyStopByClientRequest = `-- name: GetJourneyStopByClientRequest :one
SELECT stops.id, stops.journey_id, stops.place_id, stops.client_request_id,
    stops.sequence_number, stops.captured_at, stops.display_name, stops.note,
    ST_Y(stops.location::geometry)::double precision AS latitude,
    ST_X(stops.location::geometry)::double precision AS longitude,
    stops.created_at, stops.updated_at
FROM journey_stops AS stops
JOIN journeys ON journeys.id = stops.journey_id
WHERE stops.journey_id = $1 AND stops.client_request_id = $2 AND journeys.owner_id = $3
`

type GetJourneyStopByClientRequestParams struct {
	JourneyID       pgtype.UUID `json:"journey_id"`
	ClientRequestID pgtype.UUID `json:"client_request_id"`
	OwnerID         pgtype.UUID `json:"owner_id"`
}

type GetJourneyStopByClientRequestRow struct {
	ID              pgtype.UUID        `json:"id"`
	JourneyID       pgtype.UUID        `json:"journey_id"`
	PlaceID         pgtype.UUID        `json:"place_id"`
	ClientRequestID pgtype.UUID        `json:"client_request_id"`
	SequenceNumber  int64              `json:"sequence_number"`
	CapturedAt      pgtype.Timestamptz `json:"captured_at"`
	DisplayName     string             `json:"display_name"`
	Note            string             `json:"note"`
	Latitude        float64            `json:"latitude"`
	Longitude       float64            `json:"longitude"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetJourneyStopByClientRequest(ctx context.Context, arg GetJourneyStopByClientRequestParams) (GetJourneyStopByClientRequestRow, error) {
	row := q.db.QueryRow(ctx, getJourneyStopByClientRequest, arg.JourneyID, arg.ClientRequestID, arg.OwnerID)
	var i GetJourneyStopByClientRequestRow
	err := row.Scan(
		&i.ID,
		&i.JourneyID,
		&i.PlaceID,
		&i.ClientRequestID,
		&i.SequenceNumber,
		&i.CapturedAt,
		&i.DisplayName,
		&i.Note,
		&i.Latitude,
		&i.Longitude,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPlace = `-- name: GetPlace :one
SELECT id, owner_id, client_request_id, name, notes,
    ST_Y(location::geometry)::double precision AS latitude,
    ST_X(location::geometry)::double precision AS longitude,
    created_at, updated_at
FROM places
WHERE id = $1 AND owner_id = $2 AND deleted_at IS NULL
`

type GetPlaceParams struct {
	ID      pgtype.UUID `json:"id"`
	OwnerID pgtype.UUID `json:"owner_id"`
}

type GetPlaceRow struct {
	ID              pgtype.UUID        `json:"id"`
	OwnerID         pgtype.UUID        `json:"owner_id"`
	ClientRequestID pgtype.UUID        `json:"client_request_id"`
	Name            string             `json:"name"`
	Notes           string             `json:"notes"`
	Latitude        float64            `json:"latitude"`
	Longitude       float64            `json:"longitude"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetPlace(ctx context.Context, arg GetPlaceParams) (GetPlaceRow, error) {
	row := q.db.QueryRow(ctx, getPlace, arg.ID, arg.OwnerID)
	var i GetPlaceRow
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.ClientRequestID,
		&i.Name,
		&i.Notes,
		&i.Latitude,
		&i.Longitude,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listJourneyStops = `-- name: ListJourneyStops :many
SELECT stops.id, stops.journey_id, stops.place_id, stops.client_request_id,
    stops.sequence_number, stops.captured_at, stops.display_name, stops.note,
    ST_Y(stops.location::geometry)::double precision AS latitude,
    ST_X(stops.location::geometry)::double precision AS longitude,
    stops.created_at, stops.updated_at
FROM journey_stops AS stops
JOIN journeys ON journeys.id = stops.journey_id
WHERE stops.journey_id = $1 AND journeys.owner_id = $2
ORDER BY stops.sequence_number
`

type ListJourneyStopsParams struct {
	JourneyID pgtype.UUID `json:"journey_id"`
	OwnerID   pgtype.UUID `json:"owner_id"`
}

type ListJourneyStopsRow struct {
	ID              pgtype.UUID        `json:"id"`
	JourneyID       pgtype.UUID        `json:"journey_id"`
	PlaceID         pgtype.UUID        `json:"place_id"`
	ClientRequestID pgtype.UUID        `json:"client_request_id"`
	SequenceNumber  int64              `json:"sequence_number"`
	CapturedAt      pgtype.Timestamptz `json:"captured_at"`
	DisplayName     string             `json:"display_name"`
	Note            string             `json:"note"`
	Latitude        float64            `json:"latitude"`
	Longitude       float64            `json:"longitude"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ListJourneyStops(ctx context.Context, arg ListJourneyStopsParams) ([]ListJourneyStopsRow, error) {
	rows, err := q.db.Query(ctx, listJourneyStops, arg.JourneyID, arg.OwnerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListJourneyStopsRow{}
	for rows.Next() {
		var i ListJourneyStopsRow
		if err := rows.Scan(
			&i.ID,
			&i.JourneyID,
			&i.PlaceID,
			&i.ClientRequestID,
			&i.SequenceNumber,
			&i.CapturedAt,
			&i.DisplayName,
			&i.Note,
			&i.Latitude,
			&i.Longitude,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPlaces = `-- name: ListPlaces :many
SELECT id, owner_id, client_request_id, name, notes,
    ST_Y(location::geometry)::double precision AS latitude,
    ST_X(location::geometry)::double precision AS longitude,
    created_at, updated_at
FROM places
WHERE owner_id = $1 AND deleted_at IS NULL
ORDER BY created_at DESC, id DESC
LIMIT $2
`

type ListPlacesParams struct {
	OwnerID pgtype.UUID `json:"owner_id"`
	Limit   int32       `json:"limit"`
}

type ListPlacesRow struct {
	ID              pgtype.UUID        `json:"id"`
	OwnerID         pgtype.UUID        `json:"owner_id"`
	ClientRequestID pgtype.UUID        `json:"client_request_id"`
	Name            string             `json:"name"`
	Notes           string             `json:"notes"`
	Latitude        float64            `json:"latitude"`
	Longitude       float64            `json:"longitude"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ListPlaces(ctx context.Context, arg ListPlacesParams) ([]ListPlacesRow, error) {
	rows, err := q.db.Query(ctx, listPlaces, arg.OwnerID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPlacesRow{}
	for rows.Next() {
		var i ListPlacesRow
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.ClientRequestID,
			&i.Name,
			&i.Notes,
			&i.Latitude,
			&i.Longitude,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockActiveJourney = `-- name: LockActiveJourney :one
SELECT id FROM journeys
WHERE id = $1 AND owner_id = $2 AND status = 'active'
FOR UPDATE
`

type LockActiveJourneyParams struct {
	ID      pgtype.UUID `json:"id"`
	OwnerID pgtype.UUID `json:"owner_id"`
}

func (q *Queries) LockActiveJourney(ctx context.Context, arg LockActiveJourneyParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, lockActiveJourney, arg.ID, arg.OwnerID)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const nextJourneyStopSequence = `-- name: NextJourneyStopSequence :one
SELECT (coalesce(max(sequence_number), 0) + 1)::bigint
FROM journey_stops WHERE journey_id = $1
`

func (q *Queries) NextJourneyStopSequence(ctx context.Context, journeyID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, nextJourneyStopSequence, journeyID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const updateJourneyStopMetadata = `-- name: UpdateJourneyStopMetadata :one
UPDATE journey_stops AS stops
SET display_name = $4, note = $5, updated_at = now()
FROM journeys
WHERE stops.id = $1 AND stops.journey_id = $2
  AND journeys.id = stops.journey_id AND journeys.owner_id = $3
RETURNING stops.id, stops.journey_id, stops.place_id, stops.client_request_id,
    stops.sequence_number, stops.captured_at, stops.display_name, stops.note,
    ST_Y(stops.location::geometry)::double precision AS latitude,
    ST_X(stops.location::geometry)::double precision AS longitude,
    stops.created_at, stops.updated_at
`

type UpdateJourneyStopMetadataParams struct {
	ID          pgtype.UUID `json:"id"`
	JourneyID   pgtype.UUID `json:"journey_id"`
	OwnerID     pgtype.UUID `json:"owner_id"`
	DisplayName string      `json:"display_name"`
	Note        string      `json:"note"`
}

type UpdateJourneyStopMetadataRow struct {
	ID              pgtype.UUID        `json:"id"`
	JourneyID       pgtype.UUID        `json:"journey_id"`
	PlaceID         pgtype.UUID        `json:"place_id"`
	ClientRequestID pgtype.UUID        `json:"client_request_id"`
	SequenceNumber  int64              `json:"sequence_number"`
	CapturedAt      pgtype.Timestamptz `json:"captured_at"`
	DisplayName     string             `json:"display_name"`
	Note            string             `json:"note"`
	Latitude        float64            `json:"latitude"`
	Longitude       float64            `json:"longitude"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpdateJourneyStopMetadata(ctx context.Context, arg UpdateJourneyStopMetadataParams) (UpdateJourneyStopMetadataRow, error) {
	row := q.db.QueryRow(ctx, updateJourneyStopMetadata,
		arg.ID,
		arg.JourneyID,
		arg.OwnerID,
		arg.DisplayName,
		arg.Note,
	)
	var i UpdateJourneyStopMetadataRow
	err := row.Scan(
		&i.ID,
		&i.JourneyID,
		&i.PlaceID,
		&i.ClientRequestID,
		&i.SequenceNumber,
		&i.CapturedAt,
		&i.DisplayName,
		&i.Note,
		&i.Latitude,
		&i.Longitude,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updatePlace = `-- name: UpdatePlace :one
UPDATE places
SET name = $3, notes = $4, updated_at = now()
WHERE id = $1 AND owner_id = $2 AND deleted_at IS NULL
RETURNING id, owner_id, client_request_id, name, notes,
    ST_Y(location::geometry)::double precision AS latitude,
    ST_X(location::geometry)::double precision AS longitude,
    created_at, updated_at
`

type UpdatePlaceParams struct {
	ID      pgtype.UUID `json:"id"`
	OwnerID pgtype.UUID `json:"owner_id"`
	Name    string      `json:"name"`
	Notes   string      `json:"notes"`
}

type UpdatePlaceRow struct {
	ID              pgtype.UUID        `json:"id"`
	OwnerID         pgtype.UUID        `json:"owner_id"`
	ClientRequestID pgtype.UUID        `json:"client_request_id"`
	Name            string             `json:"name"`
	Notes           string             `json:"notes"`
	Latitude        float64            `json:"latitude"`
	Longitude       float64            `json:"longitude"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpdatePlace(ctx context.Context, arg UpdatePlaceParams) (UpdatePlaceRow, error) {
	row := q.db.QueryRow(ctx, updatePlace,
		arg.ID,
		arg.OwnerID,
		arg.Name,
		arg.Notes,
	)
	var i UpdatePlaceRow
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.ClientRequestID,
		&i.Name,
		&i.Notes,
		&i.Latitude,
		&i.Longitude,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
