// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	AddOutboxEvent(ctx context.Context, arg AddOutboxEventParams) (OutboxEvent, error)
	ClaimAbandonedPhotoUploads(ctx context.Context, arg ClaimAbandonedPhotoUploadsParams) ([]ClaimAbandonedPhotoUploadsRow, error)
	ClaimNextJobs(ctx context.Context, arg ClaimNextJobsParams) ([]BackgroundJob, error)
	ClearDevicePushSubscription(ctx context.Context, id pgtype.UUID) error
	CompleteJob(ctx context.Context, id int64) error
	CompleteJourney(ctx context.Context, arg CompleteJourneyParams) (Journey, error)
	CompletePhotoUpload(ctx context.Context, arg CompletePhotoUploadParams) (Photo, error)
	ConvertOutingToTrip(ctx context.Context, arg ConvertOutingToTripParams) (Journey, error)
	CreateItineraryShare(ctx context.Context, arg CreateItineraryShareParams) (ItineraryShare, error)
	CreateJourney(ctx context.Context, arg CreateJourneyParams) (Journey, error)
	CreateJourneyStop(ctx context.Context, arg CreateJourneyStopParams) (CreateJourneyStopRow, error)
	CreatePhotoUpload(ctx context.Context, arg CreatePhotoUploadParams) (Photo, error)
	CreatePlace(ctx context.Context, arg CreatePlaceParams) (CreatePlaceRow, error)
	CreateRouteSegment(ctx context.Context, arg CreateRouteSegmentParams) (pgtype.UUID, error)
	DeleteAbandonedPhotoUpload(ctx context.Context, arg DeleteAbandonedPhotoUploadParams) (int64, error)
	DeleteDevice(ctx context.Context, arg DeleteDeviceParams) (int64, error)
	DeletePlace(ctx context.Context, arg DeletePlaceParams) (int64, error)
	DeleteRouteSegments(ctx context.Context, journeyID pgtype.UUID) error
	EnqueueJob(ctx context.Context, arg EnqueueJobParams) (BackgroundJob, error)
	ExpireJourney(ctx context.Context, arg ExpireJourneyParams) (Journey, error)
	GetItineraryShareByTokenHash(ctx context.Context, tokenHash []byte) (ItineraryShare, error)
	GetJourney(ctx context.Context, arg GetJourneyParams) (Journey, error)
	GetJourneyByID(ctx context.Context, id pgtype.UUID) (Journey, error)
	GetJourneyRoute(ctx context.Context, arg GetJourneyRouteParams) ([]GetJourneyRouteRow, error)
	GetJourneyStopByClientRequest(ctx context.Context, arg GetJourneyStopByClientRequestParams) (GetJourneyStopByClientRequestRow, error)
	GetPhotoByID(ctx context.Context, id pgtype.UUID) (Photo, error)
	GetPhotoForOwner(ctx context.Context, arg GetPhotoForOwnerParams) (Photo, error)
	GetPlace(ctx context.Context, arg GetPlaceParams) (GetPlaceRow, error)
	GetReverseGeocodeCache(ctx context.Context, arg GetReverseGeocodeCacheParams) (ReverseGeocodeCache, error)
	GetUserByID(ctx context.Context, id pgtype.UUID) (User, error)
	GetUserBySubject(ctx context.Context, oidcSubject string) (User, error)
	InsertLocationSamples(ctx context.Context, arg InsertLocationSamplesParams) (int64, error)
	ListActiveOutingsBefore(ctx context.Context, arg ListActiveOutingsBeforeParams) ([]Journey, error)
	ListDevices(ctx context.Context, userID pgtype.UUID) ([]Device, error)
	ListJourneyStops(ctx context.Context, arg ListJourneyStopsParams) ([]ListJourneyStopsRow, error)
	ListJourneys(ctx context.Context, arg ListJourneysParams) ([]Journey, error)
	ListLocationSamples(ctx context.Context, arg ListLocationSamplesParams) ([]ListLocationSamplesRow, error)
	ListLocationSamplesForProcessing(ctx context.Context, journeyID pgtype.UUID) ([]ListLocationSamplesForProcessingRow, error)
	ListPhotosForShare(ctx context.Context, arg ListPhotosForShareParams) ([]ListPhotosForShareRow, error)
	ListPlaces(ctx context.Context, arg ListPlacesParams) ([]ListPlacesRow, error)
	ListPushSubscriptionsForUser(ctx context.Context, userID pgtype.UUID) ([]ListPushSubscriptionsForUserRow, error)
	ListRouteSegmentsForMatching(ctx context.Context, journeyID pgtype.UUID) ([]ListRouteSegmentsForMatchingRow, error)
	ListStopPhotos(ctx context.Context, arg ListStopPhotosParams) ([]Photo, error)
	ListUnpublishedEvents(ctx context.Context, limit int32) ([]OutboxEvent, error)
	LockActiveJourney(ctx context.Context, arg LockActiveJourneyParams) (pgtype.UUID, error)
	MarkOutboxEventPublished(ctx context.Context, id int64) error
	MarkPhotoFailed(ctx context.Context, id pgtype.UUID) error
	MarkPhotoProcessed(ctx context.Context, arg MarkPhotoProcessedParams) (Photo, error)
	NearbyPlaceCandidates(ctx context.Context, arg NearbyPlaceCandidatesParams) ([]NearbyPlaceCandidatesRow, error)
	NextJourneyStopSequence(ctx context.Context, journeyID pgtype.UUID) (int64, error)
	RequeueStaleJobs(ctx context.Context, lockedAt pgtype.Timestamptz) (int64, error)
	RetryJob(ctx context.Context, arg RetryJobParams) error
	RevokeItineraryShare(ctx context.Context, arg RevokeItineraryShareParams) (int64, error)
	UpdateJourneyLabel(ctx context.Context, arg UpdateJourneyLabelParams) (Journey, error)
	UpdateJourneyStopMetadata(ctx context.Context, arg UpdateJourneyStopMetadataParams) (UpdateJourneyStopMetadataRow, error)
	UpdateLocationSampleQuality(ctx context.Context, arg UpdateLocationSampleQualityParams) error
	UpdateMatchedRouteSegment(ctx context.Context, arg UpdateMatchedRouteSegmentParams) error
	UpdatePlace(ctx context.Context, arg UpdatePlaceParams) (UpdatePlaceRow, error)
	UpdateUserPreferences(ctx context.Context, arg UpdateUserPreferencesParams) (User, error)
	UpsertDevice(ctx context.Context, arg UpsertDeviceParams) (Device, error)
	UpsertReverseGeocodeCache(ctx context.Context, arg UpsertReverseGeocodeCacheParams) (ReverseGeocodeCache, error)
	UpsertUserFromIdentity(ctx context.Context, arg UpsertUserFromIdentityParams) (User, error)
}

var _ Querier = (*Queries)(nil)
