// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	AddOutboxEvent(ctx context.Context, arg AddOutboxEventParams) (OutboxEvent, error)
	ClaimNextJobs(ctx context.Context, arg ClaimNextJobsParams) ([]BackgroundJob, error)
	CompleteJob(ctx context.Context, id int64) error
	CompleteJourney(ctx context.Context, arg CompleteJourneyParams) (Journey, error)
	ConvertOutingToTrip(ctx context.Context, arg ConvertOutingToTripParams) (Journey, error)
	CreateJourney(ctx context.Context, arg CreateJourneyParams) (Journey, error)
	CreateJourneyStop(ctx context.Context, arg CreateJourneyStopParams) (CreateJourneyStopRow, error)
	CreatePlace(ctx context.Context, arg CreatePlaceParams) (CreatePlaceRow, error)
	DeleteDevice(ctx context.Context, arg DeleteDeviceParams) (int64, error)
	DeletePlace(ctx context.Context, arg DeletePlaceParams) (int64, error)
	EnqueueJob(ctx context.Context, arg EnqueueJobParams) (BackgroundJob, error)
	ExpireJourney(ctx context.Context, arg ExpireJourneyParams) (Journey, error)
	GetJourney(ctx context.Context, arg GetJourneyParams) (Journey, error)
	GetJourneyStopByClientRequest(ctx context.Context, arg GetJourneyStopByClientRequestParams) (GetJourneyStopByClientRequestRow, error)
	GetPlace(ctx context.Context, arg GetPlaceParams) (GetPlaceRow, error)
	GetUserByID(ctx context.Context, id pgtype.UUID) (User, error)
	GetUserBySubject(ctx context.Context, oidcSubject string) (User, error)
	ListActiveOutingsBefore(ctx context.Context, arg ListActiveOutingsBeforeParams) ([]Journey, error)
	ListDevices(ctx context.Context, userID pgtype.UUID) ([]Device, error)
	ListJourneyStops(ctx context.Context, arg ListJourneyStopsParams) ([]ListJourneyStopsRow, error)
	ListJourneys(ctx context.Context, arg ListJourneysParams) ([]Journey, error)
	ListPlaces(ctx context.Context, arg ListPlacesParams) ([]ListPlacesRow, error)
	ListUnpublishedEvents(ctx context.Context, limit int32) ([]OutboxEvent, error)
	LockActiveJourney(ctx context.Context, arg LockActiveJourneyParams) (pgtype.UUID, error)
	MarkOutboxEventPublished(ctx context.Context, id int64) error
	NextJourneyStopSequence(ctx context.Context, journeyID pgtype.UUID) (int64, error)
	RequeueStaleJobs(ctx context.Context, lockedAt pgtype.Timestamptz) (int64, error)
	RetryJob(ctx context.Context, arg RetryJobParams) error
	UpdateJourneyLabel(ctx context.Context, arg UpdateJourneyLabelParams) (Journey, error)
	UpdateJourneyStopMetadata(ctx context.Context, arg UpdateJourneyStopMetadataParams) (UpdateJourneyStopMetadataRow, error)
	UpdatePlace(ctx context.Context, arg UpdatePlaceParams) (UpdatePlaceRow, error)
	UpdateUserPreferences(ctx context.Context, arg UpdateUserPreferencesParams) (User, error)
	UpsertDevice(ctx context.Context, arg UpsertDeviceParams) (Device, error)
	UpsertUserFromIdentity(ctx context.Context, arg UpsertUserFromIdentityParams) (User, error)
}

var _ Querier = (*Queries)(nil)
