// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: sharing.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createItineraryShare = `-- name: CreateItineraryShare :one
INSERT INTO itinerary_shares (journey_id, owner_id, token_hash, snapshot, expires_at)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, journey_id, owner_id, token_hash, snapshot, expires_at, revoked_at, created_at
`

type CreateItineraryShareParams struct {
	JourneyID pgtype.UUID        `json:"journey_id"`
	OwnerID   pgtype.UUID        `json:"owner_id"`
	TokenHash []byte             `json:"token_hash"`
	Snapshot  []byte             `json:"snapshot"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateItineraryShare(ctx context.Context, arg CreateItineraryShareParams) (ItineraryShare, error) {
	row := q.db.QueryRow(ctx, createItineraryShare,
		arg.JourneyID,
		arg.OwnerID,
		arg.TokenHash,
		arg.Snapshot,
		arg.ExpiresAt,
	)
	var i ItineraryShare
	err := row.Scan(
		&i.ID,
		&i.JourneyID,
		&i.OwnerID,
		&i.TokenHash,
		&i.Snapshot,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getItineraryShareByTokenHash = `-- name: GetItineraryShareByTokenHash :one
SELECT id, journey_id, owner_id, token_hash, snapshot, expires_at, revoked_at, created_at FROM itinerary_shares
WHERE token_hash = $1 AND revoked_at IS NULL
  AND (expires_at IS NULL OR expires_at > now())
`

func (q *Queries) GetItineraryShareByTokenHash(ctx context.Context, tokenHash []byte) (ItineraryShare, error) {
	row := q.db.QueryRow(ctx, getItineraryShareByTokenHash, tokenHash)
	var i ItineraryShare
	err := row.Scan(
		&i.ID,
		&i.JourneyID,
		&i.OwnerID,
		&i.TokenHash,
		&i.Snapshot,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const listPhotosForShare = `-- name: ListPhotosForShare :many
SELECT id, stop_id, object_key, thumbnail_key
FROM photos
WHERE owner_id = $1 AND journey_id = $2 AND status = 'processed'
`

type ListPhotosForShareParams struct {
	OwnerID   pgtype.UUID `json:"owner_id"`
	JourneyID pgtype.UUID `json:"journey_id"`
}

type ListPhotosForShareRow struct {
	ID           pgtype.UUID `json:"id"`
	StopID       pgtype.UUID `json:"stop_id"`
	ObjectKey    string      `json:"object_key"`
	ThumbnailKey pgtype.Text `json:"thumbnail_key"`
}

func (q *Queries) ListPhotosForShare(ctx context.Context, arg ListPhotosForShareParams) ([]ListPhotosForShareRow, error) {
	rows, err := q.db.Query(ctx, listPhotosForShare, arg.OwnerID, arg.JourneyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPhotosForShareRow{}
	for rows.Next() {
		var i ListPhotosForShareRow
		if err := rows.Scan(
			&i.ID,
			&i.StopID,
			&i.ObjectKey,
			&i.ThumbnailKey,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeItineraryShare = `-- name: RevokeItineraryShare :execrows
UPDATE itinerary_shares SET revoked_at = now()
WHERE id = $1 AND owner_id = $2 AND revoked_at IS NULL
`

type RevokeItineraryShareParams struct {
	ID      pgtype.UUID `json:"id"`
	OwnerID pgtype.UUID `json:"owner_id"`
}

func (q *Queries) RevokeItineraryShare(ctx context.Context, arg RevokeItineraryShareParams) (int64, error) {
	result, err := q.db.Exec(ctx, revokeItineraryShare, arg.ID, arg.OwnerID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
