// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tracking.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const insertLocationSamples = `-- name: InsertLocationSamples :execrows
INSERT INTO location_samples (
    journey_id, user_id, sample_id, captured_at, location,
    accuracy_m, speed_mps, heading_deg, is_accepted, rejection_reason
)
SELECT $1, $2, points.sample_id, points.captured_at,
    ST_SetSRID(ST_MakePoint(points.longitude, points.latitude), 4326)::geography,
    points.accuracy_m, points.speed_mps, points.heading_deg,
    points.is_accepted, points.rejection_reason
FROM jsonb_to_recordset($3::jsonb) AS points(
    sample_id uuid,
    captured_at timestamptz,
    latitude double precision,
    longitude double precision,
    accuracy_m real,
    speed_mps real,
    heading_deg real,
    is_accepted boolean,
    rejection_reason text
)
ON CONFLICT (journey_id, sample_id) DO NOTHING
`

type InsertLocationSamplesParams struct {
	JourneyID pgtype.UUID `json:"journey_id"`
	UserID    pgtype.UUID `json:"user_id"`
	Points    []byte      `json:"points"`
}

func (q *Queries) InsertLocationSamples(ctx context.Context, arg InsertLocationSamplesParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertLocationSamples, arg.JourneyID, arg.UserID, arg.Points)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listLocationSamples = `-- name: ListLocationSamples :many
SELECT samples.sample_id, samples.captured_at,
    ST_Y(samples.location::geometry)::double precision AS latitude,
    ST_X(samples.location::geometry)::double precision AS longitude,
    samples.accuracy_m, samples.speed_mps, samples.heading_deg,
    samples.is_accepted, samples.rejection_reason
FROM location_samples AS samples
JOIN journeys ON journeys.id = samples.journey_id
WHERE samples.journey_id = $1 AND journeys.owner_id = $2
ORDER BY samples.captured_at, samples.id
`

type ListLocationSamplesParams struct {
	JourneyID pgtype.UUID `json:"journey_id"`
	OwnerID   pgtype.UUID `json:"owner_id"`
}

type ListLocationSamplesRow struct {
	SampleID        pgtype.UUID        `json:"sample_id"`
	CapturedAt      pgtype.Timestamptz `json:"captured_at"`
	Latitude        float64            `json:"latitude"`
	Longitude       float64            `json:"longitude"`
	AccuracyM       pgtype.Float4      `json:"accuracy_m"`
	SpeedMps        pgtype.Float4      `json:"speed_mps"`
	HeadingDeg      pgtype.Float4      `json:"heading_deg"`
	IsAccepted      bool               `json:"is_accepted"`
	RejectionReason pgtype.Text        `json:"rejection_reason"`
}

func (q *Queries) ListLocationSamples(ctx context.Context, arg ListLocationSamplesParams) ([]ListLocationSamplesRow, error) {
	rows, err := q.db.Query(ctx, listLocationSamples, arg.JourneyID, arg.OwnerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListLocationSamplesRow{}
	for rows.Next() {
		var i ListLocationSamplesRow
		if err := rows.Scan(
			&i.SampleID,
			&i.CapturedAt,
			&i.Latitude,
			&i.Longitude,
			&i.AccuracyM,
			&i.SpeedMps,
			&i.HeadingDeg,
			&i.IsAccepted,
			&i.RejectionReason,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
