// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getUserByID = `-- name: GetUserByID :one
SELECT id, oidc_subject, display_name, default_transport_mode, created_at, updated_at
FROM users
WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id pgtype.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.OidcSubject,
		&i.DisplayName,
		&i.DefaultTransportMode,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserBySubject = `-- name: GetUserBySubject :one
SELECT id, oidc_subject, display_name, default_transport_mode, created_at, updated_at
FROM users
WHERE oidc_subject = $1
`

func (q *Queries) GetUserBySubject(ctx context.Context, oidcSubject string) (User, error) {
	row := q.db.QueryRow(ctx, getUserBySubject, oidcSubject)
	var i User
	err := row.Scan(
		&i.ID,
		&i.OidcSubject,
		&i.DisplayName,
		&i.DefaultTransportMode,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUserPreferences = `-- name: UpdateUserPreferences :one
UPDATE users
SET display_name = $2,
    default_transport_mode = $3,
    updated_at = now()
WHERE id = $1
RETURNING id, oidc_subject, display_name, default_transport_mode, created_at, updated_at
`

type UpdateUserPreferencesParams struct {
	ID                   pgtype.UUID `json:"id"`
	DisplayName          string      `json:"display_name"`
	DefaultTransportMode string      `json:"default_transport_mode"`
}

func (q *Queries) UpdateUserPreferences(ctx context.Context, arg UpdateUserPreferencesParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserPreferences, arg.ID, arg.DisplayName, arg.DefaultTransportMode)
	var i User
	err := row.Scan(
		&i.ID,
		&i.OidcSubject,
		&i.DisplayName,
		&i.DefaultTransportMode,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertUserFromIdentity = `-- name: UpsertUserFromIdentity :one
INSERT INTO users (oidc_subject, display_name)
VALUES ($1, $2)
ON CONFLICT (oidc_subject) DO UPDATE
SET display_name = CASE
        WHEN EXCLUDED.display_name = '' THEN users.display_name
        ELSE EXCLUDED.display_name
    END,
    updated_at = now()
RETURNING id, oidc_subject, display_name, default_transport_mode, created_at, updated_at
`

type UpsertUserFromIdentityParams struct {
	OidcSubject string `json:"oidc_subject"`
	DisplayName string `json:"display_name"`
}

func (q *Queries) UpsertUserFromIdentity(ctx context.Context, arg UpsertUserFromIdentityParams) (User, error) {
	row := q.db.QueryRow(ctx, upsertUserFromIdentity, arg.OidcSubject, arg.DisplayName)
	var i User
	err := row.Scan(
		&i.ID,
		&i.OidcSubject,
		&i.DisplayName,
		&i.DefaultTransportMode,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
